### ISSUE TITLE
Colored signs not appearing correctly

### ISSUE THREAD

**Issue by Showdown76py** [Lennord/Essentials#3]
**Bug explaination**:
When trying to place a sign and use colored signs, it displays an unknown character.
In this example, the input was:
"&cRed color [new line]&fWhite color"

**Result**:
![image](https://user-images.githubusercontent.com/66854264/219829326-0a8940bb-f7db-4588-a809-3d0bf39ec38a.png)

**Expected**:
Showing "Red color" in red, and "White color" in white.

**Server version**:
Purpur (a fork of Paper) - 1.19.3

**Skript Addons**:
![image](https://user-images.githubusercontent.com/66854264/219829372-3d3c4746-556c-4311-ad51-b41ee6303462.png)

I'm aware that this requires _SkBee_, but I also tried with the plugin and it did not work as well.

**Comment by Lennord** [comment]
Hello, have you set the permission "essentials.sign.color" or "essentials.*" to the user who uses the colored signs?

**Comment by Lennord** [comment]
I tried to reproduce the problem and it works perfect even with your version of Purpur so I think you didn't set any of the above permissions to players.

**Comment by Lennord** [comment]
On the other hand the SkBee addon is not necessary for this script, it is only if you are obliged to use this addon for another script otherwise everything will not work, you must take the one at the download level of my script.

**Comment by Showdown76py** [comment]
Yes, they do have the permissions. The sign is modified but the symbol that is supposed to change the colors isn’t workingOn 18 Feb 2023, at 19:49, Lennord ***@***.***> wrote:﻿
Hello, have you set the permission "essentials.sign.color" or "essentials.*" to the user who uses the colored signs?

**Comment by Showdown76py** [comment]
> On the other hand the SkBee addon is not necessary for this skript, it is only if you are obliged to use this addon for another skript otherwise everything will not work, you must take the one at the download level of my skript.

I used the version that you linked in the README.md, but nothing has changed.

**Comment by Lennord** [comment]
It's weird that you have this problem, try to remove all your plugins and addons skript and put them back 1 by 1 and try the signs at the same time.
it can be one of the addons or plugins that you put in brief anyway it's not my script so unfortunately I can't help you.

**Comment by Lennord** [comment]
I am closing the invalidity issue regarding this issue.
